#!/usr/bin/env python3

#
# pyupload
#
# A simple script to upload files or directories to my webserver and return a
# link for such files. It is a wrapper for the scp program.
#
# Usage: pyupload -h
#
# Author: Andrew Northall <andrew@northall.me.uk>
# https://github.com/anorthall/
#
# License: GNU General Public Licence
#


# |-------------------------|
# |                         |
# |     Program Config      |
# |                         |
# |-------------------------|

# keyfile is the ssh private key file to use when running scp
# If set to None, it will attempt to use default keyfiles.
key = "/home/andrew/.ssh/anorthall"

# web_root is a list of strings containing the web root of the server
# you are uploading files to. If more than one string is specified then
# it will give multiple URLs for each file uploaded.
web = [
    "https://files.ilk.im/",
]

# server is the server to connect to via scp
server = "northall.me.uk"

# scp_path is the path to upload files to on the remote server
path = "www/files"

# |-------------------------|
# |                         |
# |       End Config        |
# |                         |
# |-------------------------|

from argparse import ArgumentParser

parser = ArgumentParser(
    description="Upload files to a remote server via scp and return urls for them."
)
parser.add_argument(
    "--key", 
    metavar="KEYFILE",
    type=str,
    default=key,
    help="the SSH keyfile to use when calling scp. will be passed to scp -i",
)

parser.add_argument(
    "--server", 
    type=str,
    default=server,
    help="the remote server to upload to via scp",
)

parser.add_argument(
    "--path", 
    metavar="REMOTE_PATH",
    type=str,
    default=path,
    help="the remote path to upload files to",
)

parser.add_argument(
    "--web",
    metavar="WEB_ROOT",
    type=str,
    default=web,
    help="the remote web root that should be serving files from --path",
)

args = parser.parse_args()

print(args)